# -*- coding: utf-8 -*-
"""Tail Entropy Uniform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16JK_kXInOxTnWdDhHoFb8TS3H8XmXXAQ

**Uniform-Cumulative Entropy**

n=10,000

k=50,100,300,500,1000
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time

def generate_uniform_data(n, low=0.0, high=1.0):
    return np.random.uniform(low=low, high=high, size=n)

def direct_cumulative_tail_entropy(tail_samples):
    k = len(tail_samples)
    if k < 2:
        return np.nan  # Not enough samples to estimate

    cH = 0.0
    for j in range(1, k):
        spacing = tail_samples[j] - tail_samples[j - 1]
        p_emp = j / k  # empirical CDF value at the jth step
        cH += spacing * p_emp * np.log(p_emp)
    cH = -cH  # Apply the minus sign

    w = tail_samples[-1]  # tail cutoff is the k-th order statistic
    ncH_hat = cH / w
    return ncH_hat

def estimate_LID_MLE(tail_samples):

    k = len(tail_samples)
    if k < 2:
        return np.nan

    w = tail_samples[-1]
    logs = np.log(w / tail_samples[:-1])
    LID_est = 1 / np.mean(logs)
    return LID_est

def LID_based_ncH(LID_est):

    return LID_est / ((LID_est + 1) ** 2)

# Experiment parameters
n = 10000                         # Total sample size
k_values = [50,100,300,500,1000]       # Different k (nearest-neighbor) values to test
N_iter = 500                     # Number of iterations for each k (for Monte Carlo simulation)
ground_truth_ncH = 0.25          # Ground truth normalized cumulative tail entropy for Uniform(0,1)

# Dictionaries to store results
results = {}

# For each k, perform N_iter simulations
for k in k_values:
    direct_estimates = []
    LID_based_estimates = []
    direct_times = []
    LID_based_times = []

    for i in range(N_iter):
        # Generate n points and sort them
        data = generate_uniform_data(n)
        data.sort()

        # Use the first k smallest points to define the tail region.
        tail_samples = data[:k]
        w = tail_samples[-1]  # tail cutoff is the k-th order statistic

        # Time the direct tail entropy estimator
        start = time.time()
        direct_ncH = direct_cumulative_tail_entropy(tail_samples)
        end = time.time()
        direct_times.append(end - start)

        # Time the LID estimation and LID-based tail entropy computation
        start = time.time()
        LID_est = estimate_LID_MLE(tail_samples)
        LID_ncH = LID_based_ncH(LID_est)
        end = time.time()
        LID_based_times.append(end - start)

        # Save the estimates
        direct_estimates.append(direct_ncH)
        LID_based_estimates.append(LID_ncH)

    # Convert lists to arrays for statistical computation
    direct_estimates = np.array(direct_estimates)
    LID_based_estimates = np.array(LID_based_estimates)

    # Compute statistics for the direct estimator
    direct_mean = np.nanmean(direct_estimates)
    direct_var = np.nanvar(direct_estimates)
    direct_bias2 = (direct_mean - ground_truth_ncH) ** 2
    direct_mse = direct_bias2 + direct_var

    # Compute statistics for the LID-based estimator
    LID_mean = np.nanmean(LID_based_estimates)
    LID_var = np.nanvar(LID_based_estimates)
    LID_bias2 = (LID_mean - ground_truth_ncH) ** 2
    LID_mse = LID_bias2 + LID_var

    results[k] = {
        'tail_cutoff_w': w,
        'direct_mean': direct_mean,
        'direct_variance': direct_var,
        'direct_bias^2': direct_bias2,
        'direct_MSE': direct_mse,
        'direct_avg_time_sec': np.mean(direct_times),
        'LID_mean': LID_mean,
        'LID_variance': LID_var,
        'LID_bias^2': LID_bias2,
        'LID_MSE': LID_mse,
        'LID_avg_time_sec': np.mean(LID_based_times),
    }

# Display the results for each k
for k, res in results.items():
    print(f"\nFor k = {k}:")
    print(f"  Tail cutoff w = {res['tail_cutoff_w']:.4f}")
    print("  Direct Estimator:")
    print(f"    Mean = {res['direct_mean']:.4f}")
    print(f"    Variance = {res['direct_variance']:.6f}")
    print(f"    Squared Bias = {res['direct_bias^2']:.6f}")
    print(f"    MSE = {res['direct_MSE']:.6f}")
    print(f"    Avg. time = {res['direct_avg_time_sec']:.6e} sec")
    print("  LID-based Estimator:")
    print(f"    Mean = {res['LID_mean']:.4f}")
    print(f"    Variance = {res['LID_variance']:.6f}")
    print(f"    Squared Bias = {res['LID_bias^2']:.6f}")
    print(f"    MSE = {res['LID_MSE']:.10f}")
    print(f"    Avg. time = {res['LID_avg_time_sec']:.6e} sec")

"""**Uniform-Cumulative Entropy**

n=1000

k=10,20,50,75,100
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time

def generate_uniform_data(n, low=0.0, high=1.0):
    """Generate n samples from a Uniform(low, high) distribution."""
    return np.random.uniform(low=low, high=high, size=n)

def direct_cumulative_tail_entropy(tail_samples):
    """
    Estimate the cumulative tail entropy from tail samples using spacings.

    Parameters:
        tail_samples: 1D NumPy array of sorted samples in the tail region [0, w],
                      where w = tail_samples[-1].

    Returns:
        ncH_hat: normalized cumulative tail entropy (cumulative tail entropy divided by w).
    """
    k = len(tail_samples)
    if k < 2:
        return np.nan  # Not enough samples to estimate

    cH = 0.0
    for j in range(1, k):
        spacing = tail_samples[j] - tail_samples[j - 1]
        p_emp = j / k  # empirical CDF value at the jth step
        cH += spacing * p_emp * np.log(p_emp)
    cH = -cH  # Apply the minus sign

    w = tail_samples[-1]  # tail cutoff is the k-th order statistic
    ncH_hat = cH / w
    return ncH_hat

def estimate_LID_MLE(tail_samples):

    k = len(tail_samples)
    if k < 2:
        return np.nan

    w = tail_samples[-1]
    logs = np.log(w / tail_samples[:-1])
    LID_est = 1 / np.mean(logs)
    return LID_est

def LID_based_ncH(LID_est):

    return LID_est / ((LID_est + 1) ** 2)

# Experiment parameters
n = 1000                         # Total sample size
k_values = [10,20,50,75,100]       # Different k (nearest-neighbor) values to test
N_iter = 500                     # Number of iterations for each k (for Monte Carlo simulation)
ground_truth_ncH = 0.25          # Ground truth normalized cumulative tail entropy for Uniform(0,1)

# Dictionaries to store results
results = {}

# For each k, perform N_iter simulations
for k in k_values:
    direct_estimates = []
    LID_based_estimates = []
    direct_times = []
    LID_based_times = []

    for i in range(N_iter):
        # Generate n points and sort them
        data = generate_uniform_data(n)
        data.sort()

        # Use the first k smallest points to define the tail region.
        tail_samples = data[:k]
        w = tail_samples[-1]  # tail cutoff is the k-th order statistic

        # Time the direct tail entropy estimator
        start = time.time()
        direct_ncH = direct_cumulative_tail_entropy(tail_samples)
        end = time.time()
        direct_times.append(end - start)

        # Time the LID estimation and LID-based tail entropy computation
        start = time.time()
        LID_est = estimate_LID_MLE(tail_samples)
        LID_ncH = LID_based_ncH(LID_est)
        end = time.time()
        LID_based_times.append(end - start)

        # Save the estimates
        direct_estimates.append(direct_ncH)
        LID_based_estimates.append(LID_ncH)

    # Convert lists to arrays for statistical computation
    direct_estimates = np.array(direct_estimates)
    LID_based_estimates = np.array(LID_based_estimates)

    # Compute statistics for the direct estimator
    direct_mean = np.nanmean(direct_estimates)
    direct_var = np.nanvar(direct_estimates)
    direct_bias2 = (direct_mean - ground_truth_ncH) ** 2
    direct_mse = direct_bias2 + direct_var

    # Compute statistics for the LID-based estimator
    LID_mean = np.nanmean(LID_based_estimates)
    LID_var = np.nanvar(LID_based_estimates)
    LID_bias2 = (LID_mean - ground_truth_ncH) ** 2
    LID_mse = LID_bias2 + LID_var

    results[k] = {
        'tail_cutoff_w': w,
        'direct_mean': direct_mean,
        'direct_variance': direct_var,
        'direct_bias^2': direct_bias2,
        'direct_MSE': direct_mse,
        'direct_avg_time_sec': np.mean(direct_times),
        'LID_mean': LID_mean,
        'LID_variance': LID_var,
        'LID_bias^2': LID_bias2,
        'LID_MSE': LID_mse,
        'LID_avg_time_sec': np.mean(LID_based_times),
    }

# Display the results for each k
for k, res in results.items():
    print(f"\nFor k = {k}:")
    print(f"  Tail cutoff w = {res['tail_cutoff_w']:.4f}")
    print("  Direct Estimator:")
    print(f"    Mean = {res['direct_mean']:.4f}")
    print(f"    Variance = {res['direct_variance']:.6f}")
    print(f"    Squared Bias = {res['direct_bias^2']:.6f}")
    print(f"    MSE = {res['direct_MSE']:.6f}")
    print(f"    Avg. time = {res['direct_avg_time_sec']:.6e} sec")
    print("  LID-based Estimator:")
    print(f"    Mean = {res['LID_mean']:.4f}")
    print(f"    Variance = {res['LID_variance']:.6f}")
    print(f"    Squared Bias = {res['LID_bias^2']:.6f}")
    print(f"    MSE = {res['LID_MSE']:.6f}")
    print(f"    Avg. time = {res['LID_avg_time_sec']:.6e} sec")

"""
**Truncated-Cumulative Entropy**

n=10,000

k=50,100,300,500,1000"""

import numpy as np
import time
import sympy as sp

def generate_truncated_exponential(n, lambd=1.0):
    """
    Generate n samples from a truncated exponential distribution on [0, 1] with rate lambda.
    """
    u = np.random.uniform(0, 1, size=n)
    return -np.log(1 - u * (1 - np.exp(-lambd))) / lambd

def direct_cumulative_tail_entropy(tail_samples):
    """
    Estimate the normalized cumulative tail entropy using spacings for the tail samples.
    """
    k = len(tail_samples)
    if k < 2:
        return np.nan

    cH = 0.0
    for j in range(1, k):
        spacing = tail_samples[j] - tail_samples[j - 1]
        p_emp = j / k
        cH += spacing * p_emp * np.log(p_emp)
    cH = -cH
    w = tail_samples[-1]
    return cH / w

def estimate_LID_MLE(tail_samples):
    """
    Estimate local intrinsic dimensionality using the Hill estimator.
    """
    k = len(tail_samples)
    if k < 2:
        return np.nan
    w = tail_samples[-1]
    logs = np.log(w / tail_samples[:-1])
    return 1 / np.mean(logs)

def LID_based_ncH(LID_est):
    """
    LID-based normalized cumulative tail entropy estimate.
    """
    return LID_est / ((LID_est + 1) ** 2)

from scipy.integrate import quad

def compute_cH_trunc_exp_groundtruth(w_val, lambd_val):
    """
    Compute the true normalized cumulative tail entropy for the truncated exponential distribution
    using numerical integration.
    """
    A = 1 - np.exp(-lambd_val * w_val)

    def integrand(u):
        if u == 0:
            return 0.0  # Handle the singularity at u = 0
        return (u * np.log(u)) / (1 - u * A)

    integral, _ = quad(integrand, 0, 1, limit=100, epsabs=1e-10, epsrel=1e-10)
    cH = -A / lambd_val * integral
    return cH


# Parameters
n = 10000
k_values = [50,100,300,500,1000]
N_iter = 500
lambd = 2.0  # Truncation rate

results = {}

# Run experiments
for k in k_values:
    direct_estimates = []
    LID_estimates = []
    direct_times = []
    LID_times = []

    for _ in range(N_iter):
        data = generate_truncated_exponential(n, lambd=lambd)
        data.sort()
        tail_samples = data[:k]
        w = tail_samples[-1]

        # Direct estimation
        start = time.time()
        ncH_direct = direct_cumulative_tail_entropy(tail_samples)
        direct_times.append(time.time() - start)

        # LID-based estimation
        start = time.time()
        LID_est = estimate_LID_MLE(tail_samples)
        ncH_LID = LID_based_ncH(LID_est)
        LID_times.append(time.time() - start)

        direct_estimates.append(ncH_direct)
        LID_estimates.append(ncH_LID)

    # Convert to arrays
    direct_estimates = np.array(direct_estimates)
    LID_estimates = np.array(LID_estimates)

    # Use numerical ground truth
    ncH_true = compute_cH_trunc_exp_groundtruth(w, lambd)/w

    results[k] = {
        'tail_cutoff_w': w,
        'ground_truth_ncH': ncH_true,
        'direct_mean': np.nanmean(direct_estimates),
        'direct_var': np.nanvar(direct_estimates),
        'direct_bias2': (np.nanmean(direct_estimates) - ncH_true) ** 2,
        'direct_MSE': np.nanvar(direct_estimates) + (np.nanmean(direct_estimates) - ncH_true) ** 2,
        'direct_time': np.mean(direct_times),
        'LID_mean': np.nanmean(LID_estimates),
        'LID_var': np.nanvar(LID_estimates),
        'LID_bias2': (np.nanmean(LID_estimates) - ncH_true) ** 2,
        'LID_MSE': np.nanvar(LID_estimates) + (np.nanmean(LID_estimates) - ncH_true) ** 2,
        'LID_time': np.mean(LID_times),
    }

# Print summary
for k, r in results.items():
    print(f"\nFor k = {k} (tail cutoff w ≈ {r['tail_cutoff_w']:.4f}):")
    print(f"  Ground Truth (from average direct): {r['ground_truth_ncH']:.4f}")
    print("  Direct Estimator:")
    print(f"    Mean = {r['direct_mean']:.4f}, Variance = {r['direct_var']:.6f}")
    print(f"    Bias^2 = {r['direct_bias2']:.6f}, MSE = {r['direct_MSE']:.6f}")
    print(f"    Avg Time = {r['direct_time']:.6e} sec")
    print("  LID-based Estimator:")
    print(f"    Mean = {r['LID_mean']:.4f}, Variance = {r['LID_var']:.6f}")
    print(f"    Bias^2 = {r['LID_bias2']:.6f}, MSE = {r['LID_MSE']:.10f}")
    print(f"    Avg Time = {r['LID_time']:.6e} sec")

"""
**Truncated-Cumulative Entropy**

n=1000

k=10,20,50,75,100"""

import numpy as np
import time
import sympy as sp

def generate_truncated_exponential(n, lambd=1.0):
    """
    Generate n samples from a truncated exponential distribution on [0, 1] with rate lambda.
    """
    u = np.random.uniform(0, 1, size=n)
    return -np.log(1 - u * (1 - np.exp(-lambd))) / lambd

def direct_cumulative_tail_entropy(tail_samples):
    """
    Estimate the normalized cumulative tail entropy using spacings for the tail samples.
    """
    k = len(tail_samples)
    if k < 2:
        return np.nan

    cH = 0.0
    for j in range(1, k):
        spacing = tail_samples[j] - tail_samples[j - 1]
        p_emp = j / k
        cH += spacing * p_emp * np.log(p_emp)
    cH = -cH
    w = tail_samples[-1]
    return cH / w

def estimate_LID_MLE(tail_samples):
    """
    Estimate local intrinsic dimensionality using the Hill estimator.
    """
    k = len(tail_samples)
    if k < 2:
        return np.nan
    w = tail_samples[-1]
    logs = np.log(w / tail_samples[:-1])
    return 1 / np.mean(logs)

def LID_based_ncH(LID_est):
    """
    LID-based normalized cumulative tail entropy estimate.
    """
    return LID_est / ((LID_est + 1) ** 2)

from scipy.integrate import quad

def compute_cH_trunc_exp_groundtruth(w_val, lambd_val):
    """
    Compute the true normalized cumulative tail entropy for the truncated exponential distribution
    using numerical integration.
    """
    A = 1 - np.exp(-lambd_val * w_val)

    def integrand(u):
        if u == 0:
            return 0.0  # Handle the singularity at u = 0
        return (u * np.log(u)) / (1 - u * A)

    integral, _ = quad(integrand, 0, 1, limit=100, epsabs=1e-10, epsrel=1e-10)
    cH = -A / lambd_val * integral
    return cH


# Parameters
n = 1000
k_values = [10,20,50,75,100]
N_iter = 500
lambd = 2.0  # Truncation rate

results = {}

# Run experiments
for k in k_values:
    direct_estimates = []
    LID_estimates = []
    direct_times = []
    LID_times = []

    for _ in range(N_iter):
        data = generate_truncated_exponential(n, lambd=lambd)
        data.sort()
        tail_samples = data[:k]
        w = tail_samples[-1]

        # Direct estimation
        start = time.time()
        ncH_direct = direct_cumulative_tail_entropy(tail_samples)
        direct_times.append(time.time() - start)

        # LID-based estimation
        start = time.time()
        LID_est = estimate_LID_MLE(tail_samples)
        ncH_LID = LID_based_ncH(LID_est)
        LID_times.append(time.time() - start)

        direct_estimates.append(ncH_direct)
        LID_estimates.append(ncH_LID)

    # Convert to arrays
    direct_estimates = np.array(direct_estimates)
    LID_estimates = np.array(LID_estimates)

    # Use numerical ground truth
    ncH_true = compute_cH_trunc_exp_groundtruth(w, lambd)/w

    results[k] = {
        'tail_cutoff_w': w,
        'ground_truth_ncH': ncH_true,
        'direct_mean': np.nanmean(direct_estimates),
        'direct_var': np.nanvar(direct_estimates),
        'direct_bias2': (np.nanmean(direct_estimates) - ncH_true) ** 2,
        'direct_MSE': np.nanvar(direct_estimates) + (np.nanmean(direct_estimates) - ncH_true) ** 2,
        'direct_time': np.mean(direct_times),
        'LID_mean': np.nanmean(LID_estimates),
        'LID_var': np.nanvar(LID_estimates),
        'LID_bias2': (np.nanmean(LID_estimates) - ncH_true) ** 2,
        'LID_MSE': np.nanvar(LID_estimates) + (np.nanmean(LID_estimates) - ncH_true) ** 2,
        'LID_time': np.mean(LID_times),
    }

# Print summary
for k, r in results.items():
    print(f"\nFor k = {k} (tail cutoff w ≈ {r['tail_cutoff_w']:.4f}):")
    print(f"  Ground Truth (from average direct): {r['ground_truth_ncH']:.4f}")
    print("  Direct Estimator:")
    print(f"    Mean = {r['direct_mean']:.4f}, Variance = {r['direct_var']:.6f}")
    print(f"    Bias^2 = {r['direct_bias2']:.6f}, MSE = {r['direct_MSE']:.6f}")
    print(f"    Avg Time = {r['direct_time']:.6e} sec")
    print("  LID-based Estimator:")
    print(f"    Mean = {r['LID_mean']:.4f}, Variance = {r['LID_var']:.6f}")
    print(f"    Bias^2 = {r['LID_bias2']:.6f}, MSE = {r['LID_MSE']:.6f}")
    print(f"    Avg Time = {r['LID_time']:.6e} sec")

"""**Uniform-HP Entropy**

n=10,000

k=50,75,100,150,200
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
from scipy.special import psi  # digamma function

# Define Euler-Mascheroni constant manually
EULER_GAMMA = 0.57721566490153286060651209

def generate_uniform_data(n, low=0.0, high=1.0):
    """Generate n samples from a Uniform(low, high) distribution."""
    return np.random.uniform(low=low, high=high, size=n)


from sklearn.neighbors import NearestNeighbors

def kl_entropy_estimator(data, k=1):
    """
    Kozachenko–Leonenko entropy estimator for 1D data.

    Parameters:
        data (array): 1D array of sample points in [0, w]
        k (int): number of nearest neighbors (usually k=1 for KL)

    Returns:
        Estimated differential entropy H(F,w)
    """
    n = len(data)
    data = data.reshape(-1, 1)

    # Compute distance to k-th nearest neighbor
    nbrs = NearestNeighbors(n_neighbors=k+1).fit(data)
    distances, _ = nbrs.kneighbors(data)

    # Skip the first column (distance to self is 0)
    rho = distances[:, k]  # distance to k-th nearest neighbor

    # Avoid log(0)
    rho = np.clip(rho, 1e-10, None)

    Hn = (1 / n) * np.sum(np.log(rho)) + psi(n) - psi(1) + np.log(2)
    return Hn

def direct_tail_entropy_power(tail_samples, total_samples):
    k = len(tail_samples)
    if k < 2 or total_samples < k:
        return np.nan
    w = tail_samples[-1]
    if w <= 0:
        return np.nan

    # Compute spacings
    spacings = np.diff(tail_samples)
    # Clip spacings to avoid log(0) or negative values
    spacings = np.maximum(spacings, 1e-10)

    log_geo_mean = np.mean(np.log(spacings))

    # Dimension m = 1 → c_1(m) = 2
    m = 1
    c_m = 2

    # Apply the KL estimator formula
    tail_entropy = kl_entropy_estimator(tail_samples)
    HP_tail = np.exp(tail_entropy)
    nHP_hat = HP_tail / w


    # Compute estimated tail entropy power and normalize
    #HP_direct = np.exp(H_direct)  # Tail entropy power: exp(estimated H)
    #nHP_hat = HP_direct / w       # Normalize by tail cutoff w
    return nHP_hat

def estimate_LID_MLE(tail_samples):

    k = len(tail_samples)
    if k < 2:
        return np.nan
    w = tail_samples[-1]
    if w <= 0:
        return np.nan
    logs = np.log(w / tail_samples[:-1])
    LID_est = 1 / np.mean(logs)
    return LID_est

def LID_based_nHP(LID_est):

    if LID_est <= 0:
        return np.nan
    return (1 / LID_est) * np.exp(1 - (1 / LID_est))

# Experiment parameters
n = 10000             # total sample size
k_values = [50,100,300,500,1000]  # different k values
N_iter = 500          # number of Monte Carlo iterations
# Ground truth for Uniform(0,1): normalized tail entropy power = 1
ground_truth_nHP = 1.0

results = {}

# Monte Carlo simulation for each k
for k in k_values:
    direct_estimates = []
    LID_based_estimates = []
    direct_times = []
    LID_times = []

    for i in range(N_iter):
        # Generate data and sort
        data = generate_uniform_data(n)
        data.sort()
        # Define tail region: first k points, with tail cutoff w = X_(k)
        tail_samples = data[:k]
        w = tail_samples[-1]

        # Direct tail entropy power estimation
        start_time = time.time()
        nHP_direct = direct_tail_entropy_power(tail_samples, n)
        direct_times.append(time.time() - start_time)

        # LID-based estimation
        start_time = time.time()
        LID_est = estimate_LID_MLE(tail_samples)
        nHP_LID = LID_based_nHP(LID_est)
        LID_times.append(time.time() - start_time)

        direct_estimates.append(nHP_direct)
        LID_based_estimates.append(nHP_LID)

    # Compute statistics
    direct_estimates = np.array(direct_estimates)
    LID_based_estimates = np.array(LID_based_estimates)

    direct_mean = np.nanmean(direct_estimates)
    direct_var = np.nanvar(direct_estimates)
    direct_bias2 = (direct_mean - ground_truth_nHP) ** 2
    direct_MSE = direct_bias2 + direct_var

    LID_mean = np.nanmean(LID_based_estimates)
    LID_var = np.nanvar(LID_based_estimates)
    LID_bias2 = (LID_mean - ground_truth_nHP) ** 2
    LID_MSE = LID_bias2 + LID_var

    results[k] = {
        'tail_cutoff_w': w,
        'direct_mean': direct_mean,
        'direct_variance': direct_var,
        'direct_bias^2': direct_bias2,
        'direct_MSE': direct_MSE,
        'direct_avg_time_sec': np.mean(direct_times),
        'LID_mean': LID_mean,
        'LID_variance': LID_var,
        'LID_bias^2': LID_bias2,
        'LID_MSE': LID_MSE,
        'LID_avg_time_sec': np.mean(LID_times),
    }

# Print the results for each k
for k, res in results.items():
    print(f"\nFor k = {k}:")
    print(f"  Tail cutoff w = {res['tail_cutoff_w']:.4f}")
    print("  Direct Estimator:")
    print(f"    Mean normalized tail entropy power = {res['direct_mean']:.4f}")
    print(f"    Variance = {res['direct_variance']:.6f}")
    print(f"    Squared Bias = {res['direct_bias^2']:.6f}")
    print(f"    MSE = {res['direct_MSE']:.6f}")
    print(f"    Avg. computation time = {res['direct_avg_time_sec']:.6e} sec")
    print("  LID-based Estimator:")
    print(f"    Mean normalized tail entropy power = {res['LID_mean']:.4f}")
    print(f"    Variance = {res['LID_variance']:.6f}")
    print(f"    Squared Bias = {res['LID_bias^2']:.6f}")
    print(f"    MSE = {res['LID_MSE']:.10f}")
    print(f"    Avg. computation time = {res['LID_avg_time_sec']:.6e} sec")

# Plot MSE vs. k
plt.figure(figsize=(10, 6))
plt.plot(k_values, [results[k]['direct_MSE'] for k in k_values], label='Direct Estimator MSE', marker='o')
plt.plot(k_values, [results[k]['LID_MSE'] for k in k_values], label='LID-based Estimator MSE', marker='s')
plt.xlabel('k (Number of Tail Samples)')
plt.ylabel('Mean Squared Error')
plt.title('MSE of Normalized Tail Entropy Power Estimators')
plt.legend()
plt.grid(True)
plt.savefig('tail_entropy_power_mse.png')

"""**Uniform-HP Entropy**

n=1000

k=10,20,50,75,100
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
from scipy.special import psi  # digamma function

# Define Euler-Mascheroni constant manually
EULER_GAMMA = 0.57721566490153286060651209

def generate_uniform_data(n, low=0.0, high=1.0):
    """Generate n samples from a Uniform(low, high) distribution."""
    return np.random.uniform(low=low, high=high, size=n)


from sklearn.neighbors import NearestNeighbors

def kl_entropy_estimator(data, k=1):
    """
    Kozachenko–Leonenko entropy estimator for 1D data.

    Parameters:
        data (array): 1D array of sample points in [0, w]
        k (int): number of nearest neighbors (usually k=1 for KL)

    Returns:
        Estimated differential entropy H(F,w)
    """
    n = len(data)
    data = data.reshape(-1, 1)

    # Compute distance to k-th nearest neighbor
    nbrs = NearestNeighbors(n_neighbors=k+1).fit(data)
    distances, _ = nbrs.kneighbors(data)

    # Skip the first column (distance to self is 0)
    rho = distances[:, k]  # distance to k-th nearest neighbor

    # Avoid log(0)
    rho = np.clip(rho, 1e-10, None)

    Hn = (1 / n) * np.sum(np.log(rho)) + psi(n) - psi(1) + np.log(2)
    return Hn

def direct_tail_entropy_power(tail_samples, total_samples):

    k = len(tail_samples)
    if k < 2 or total_samples < k:
        return np.nan
    w = tail_samples[-1]
    if w <= 0:
        return np.nan

    # Compute spacings
    spacings = np.diff(tail_samples)
    # Clip spacings to avoid log(0) or negative values
    spacings = np.maximum(spacings, 1e-10)

    log_geo_mean = np.mean(np.log(spacings))

    # Dimension m = 1 → c_1(m) = 2
    m = 1
    c_m = 2

    # Apply the KL estimator formula
    tail_entropy = kl_entropy_estimator(tail_samples)
    HP_tail = np.exp(tail_entropy)
    nHP_hat = HP_tail / w


    # Compute estimated tail entropy power and normalize
    #HP_direct = np.exp(H_direct)  # Tail entropy power: exp(estimated H)
    #nHP_hat = HP_direct / w       # Normalize by tail cutoff w
    return nHP_hat

def estimate_LID_MLE(tail_samples):

    k = len(tail_samples)
    if k < 2:
        return np.nan
    w = tail_samples[-1]
    if w <= 0:
        return np.nan
    logs = np.log(w / tail_samples[:-1])
    LID_est = 1 / np.mean(logs)
    return LID_est

def LID_based_nHP(LID_est):

    if LID_est <= 0:
        return np.nan
    return (1 / LID_est) * np.exp(1 - (1 / LID_est))

# Experiment parameters
n = 1000             # total sample size
k_values = [10,20,50,75,100]  # different k values
N_iter = 500          # number of Monte Carlo iterations
# Ground truth for Uniform(0,1): normalized tail entropy power = 1
ground_truth_nHP = 1.0

results = {}

# Monte Carlo simulation for each k
for k in k_values:
    direct_estimates = []
    LID_based_estimates = []
    direct_times = []
    LID_times = []

    for i in range(N_iter):
        # Generate data and sort
        data = generate_uniform_data(n)
        data.sort()
        # Define tail region: first k points, with tail cutoff w = X_(k)
        tail_samples = data[:k]
        w = tail_samples[-1]

        # Direct tail entropy power estimation
        start_time = time.time()
        nHP_direct = direct_tail_entropy_power(tail_samples, n)
        direct_times.append(time.time() - start_time)

        # LID-based estimation
        start_time = time.time()
        LID_est = estimate_LID_MLE(tail_samples)
        nHP_LID = LID_based_nHP(LID_est)
        LID_times.append(time.time() - start_time)

        direct_estimates.append(nHP_direct)
        LID_based_estimates.append(nHP_LID)

    # Compute statistics
    direct_estimates = np.array(direct_estimates)
    LID_based_estimates = np.array(LID_based_estimates)

    direct_mean = np.nanmean(direct_estimates)
    direct_var = np.nanvar(direct_estimates)
    direct_bias2 = (direct_mean - ground_truth_nHP) ** 2
    direct_MSE = direct_bias2 + direct_var

    LID_mean = np.nanmean(LID_based_estimates)
    LID_var = np.nanvar(LID_based_estimates)
    LID_bias2 = (LID_mean - ground_truth_nHP) ** 2
    LID_MSE = LID_bias2 + LID_var

    results[k] = {
        'tail_cutoff_w': w,
        'direct_mean': direct_mean,
        'direct_variance': direct_var,
        'direct_bias^2': direct_bias2,
        'direct_MSE': direct_MSE,
        'direct_avg_time_sec': np.mean(direct_times),
        'LID_mean': LID_mean,
        'LID_variance': LID_var,
        'LID_bias^2': LID_bias2,
        'LID_MSE': LID_MSE,
        'LID_avg_time_sec': np.mean(LID_times),
    }

# Print the results for each k
for k, res in results.items():
    print(f"\nFor k = {k}:")
    print(f"  Tail cutoff w = {res['tail_cutoff_w']:.4f}")
    print("  Direct Estimator:")
    print(f"    Mean normalized tail entropy power = {res['direct_mean']:.4f}")
    print(f"    Variance = {res['direct_variance']:.6f}")
    print(f"    Squared Bias = {res['direct_bias^2']:.6f}")
    print(f"    MSE = {res['direct_MSE']:.6f}")
    print(f"    Avg. computation time = {res['direct_avg_time_sec']:.6e} sec")
    print("  LID-based Estimator:")
    print(f"    Mean normalized tail entropy power = {res['LID_mean']:.4f}")
    print(f"    Variance = {res['LID_variance']:.6f}")
    print(f"    Squared Bias = {res['LID_bias^2']:.6f}")
    print(f"    MSE = {res['LID_MSE']:.6f}")
    print(f"    Avg. computation time = {res['LID_avg_time_sec']:.6e} sec")

# Plot MSE vs. k
plt.figure(figsize=(10, 6))
plt.plot(k_values, [results[k]['direct_MSE'] for k in k_values], label='Direct Estimator MSE', marker='o')
plt.plot(k_values, [results[k]['LID_MSE'] for k in k_values], label='LID-based Estimator MSE', marker='s')
plt.xlabel('k (Number of Tail Samples)')
plt.ylabel('Mean Squared Error')
plt.title('MSE of Normalized Tail Entropy Power Estimators')
plt.legend()
plt.grid(True)
plt.savefig('tail_entropy_power_mse.png')

"""**Truncated-HP Entropy**

n=10,000

"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
from scipy.special import psi  # digamma function

# Define Euler-Mascheroni constant manually
EULER_GAMMA = 0.57721566490153286060651209

def generate_truncated_exponential_data(n, lam=1.0):

    u = np.random.uniform(0, 1, size=n)
    return -np.log(1 - u * (1 - np.exp(-lam))) / lam



from sklearn.neighbors import NearestNeighbors

def kl_entropy_estimator(data, k=1):

    n = len(data)
    data = data.reshape(-1, 1)

    # Compute distance to k-th nearest neighbor
    nbrs = NearestNeighbors(n_neighbors=k+1).fit(data)
    distances, _ = nbrs.kneighbors(data)

    # Skip the first column (distance to self is 0)
    rho = distances[:, k]  # distance to k-th nearest neighbor

    # Avoid log(0)
    rho = np.clip(rho, 1e-10, None)

    Hn = (1 / n) * np.sum(np.log(rho)) + psi(n) - psi(1) + np.log(2)
    return Hn

def direct_tail_entropy_power(tail_samples, total_samples):

    k = len(tail_samples)
    if k < 2 or total_samples < k:
        return np.nan
    w = tail_samples[-1]
    if w <= 0:
        return np.nan

    # Compute spacings
    spacings = np.diff(tail_samples)
    # Clip spacings to avoid log(0) or negative values
    spacings = np.maximum(spacings, 1e-10)

    log_geo_mean = np.mean(np.log(spacings))

    # Dimension m = 1 → c_1(m) = 2
    m = 1
    c_m = 2

    # Apply the KL estimator formula
    tail_entropy = kl_entropy_estimator(tail_samples)
    HP_tail = np.exp(tail_entropy)
    nHP_hat = HP_tail / w


    # Compute estimated tail entropy power and normalize
    #HP_direct = np.exp(H_direct)  # Tail entropy power: exp(estimated H)
    #nHP_hat = HP_direct / w       # Normalize by tail cutoff w
    return nHP_hat

def estimate_LID_MLE(tail_samples):

    k = len(tail_samples)
    if k < 2:
        return np.nan
    w = tail_samples[-1]
    if w <= 0:
        return np.nan
    logs = np.log(w / tail_samples[:-1])
    LID_est = 1 / np.mean(logs)
    return LID_est

def LID_based_nHP(LID_est):

    if LID_est <= 0:
        return np.nan
    return (1 / LID_est) * np.exp(1 - (1 / LID_est))

def compute_HP_trunc_exp_groundtruth(w, lambd):

    A = (1 - np.exp(-lambd * w))
    HP = (A/lambd) * np.exp(1 - ((lambd * w * np.exp(-lambd * w)) / A))
    nHP = HP / w
    return HP, nHP

# Experiment parameters
n = 10000             # total sample size
k_values = [50,100,300,500,1000]  # different k values
N_iter = 500          # number of Monte Carlo iterations

results = {}

# Monte Carlo simulation for each k
for k in k_values:
    direct_estimates = []
    LID_based_estimates = []
    direct_times = []
    LID_times = []

    for i in range(N_iter):
        # Generate data and sort
        data = generate_truncated_exponential_data(n,2)
        data.sort()
        # Define tail region: first k points, with tail cutoff w = X_(k)
        tail_samples = data[:k]
        w = tail_samples[-1]
        _, ground_truth_nHP = compute_HP_trunc_exp_groundtruth(w, 2)


        # Direct tail entropy power estimation
        start_time = time.time()
        nHP_direct = direct_tail_entropy_power(tail_samples, n)
        direct_times.append(time.time() - start_time)

        # LID-based estimation
        start_time = time.time()
        LID_est = estimate_LID_MLE(tail_samples)
        nHP_LID = LID_based_nHP(LID_est)
        LID_times.append(time.time() - start_time)

        direct_estimates.append(nHP_direct)
        LID_based_estimates.append(nHP_LID)

    # Compute statistics
    direct_estimates = np.array(direct_estimates)
    LID_based_estimates = np.array(LID_based_estimates)

    direct_mean = np.nanmean(direct_estimates)
    direct_var = np.nanvar(direct_estimates)
    direct_bias2 = (direct_mean - ground_truth_nHP) ** 2
    direct_MSE = direct_bias2 + direct_var

    LID_mean = np.nanmean(LID_based_estimates)
    LID_var = np.nanvar(LID_based_estimates)
    LID_bias2 = (LID_mean - ground_truth_nHP) ** 2
    LID_MSE = LID_bias2 + LID_var

    results[k] = {
    'tail_cutoff_w': w,
    'ground_truth_nHP': ground_truth_nHP,
    'direct_mean': direct_mean,
    'direct_variance': direct_var,
    'direct_bias^2': direct_bias2,
    'direct_MSE': direct_MSE,
    'direct_avg_time_sec': np.mean(direct_times),
    'LID_mean': LID_mean,
    'LID_variance': LID_var,
    'LID_bias^2': LID_bias2,
    'LID_MSE': LID_MSE,
    'LID_avg_time_sec': np.mean(LID_times),
}


# Print the results for each k
for k, res in results.items():
    print(f"\nFor k = {k}:")
    print(f"    Ground truth tail entropy power = {res['ground_truth_nHP']:.8f}")
    print(f"  Tail cutoff w = {res['tail_cutoff_w']:.4f}")
    print("  Direct Estimator:")
    print(f"    Mean normalized tail entropy power = {res['direct_mean']:.4f}")
    print(f"    Variance = {res['direct_variance']:.6f}")
    print(f"    Squared Bias = {res['direct_bias^2']:.6f}")
    print(f"    MSE = {res['direct_MSE']:.6f}")
    print(f"    Avg. computation time = {res['direct_avg_time_sec']:.6e} sec")
    print("  LID-based Estimator:")
    print(f"    Mean normalized tail entropy power = {res['LID_mean']:.4f}")
    print(f"    Variance = {res['LID_variance']:.6f}")
    print(f"    Squared Bias = {res['LID_bias^2']:.6f}")
    print(f"    MSE = {res['LID_MSE']:.6f}")
    print(f"    Avg. computation time = {res['LID_avg_time_sec']:.6e} sec")

# Plot MSE vs. k
plt.figure(figsize=(10, 6))
plt.plot(k_values, [results[k]['direct_MSE'] for k in k_values], label='Direct Estimator MSE', marker='o')
plt.plot(k_values, [results[k]['LID_MSE'] for k in k_values], label='LID-based Estimator MSE', marker='s')
plt.xlabel('k (Number of Tail Samples)')
plt.ylabel('Mean Squared Error')
plt.title('MSE of Normalized Tail Entropy Power Estimators')
plt.legend()
plt.grid(True)
plt.savefig('tail_entropy_power_mse.png')

"""**Truncated-HP Entropy**

n=1000

k=10,20,50,75,100
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
from scipy.special import psi  # digamma function

# Define Euler-Mascheroni constant manually
EULER_GAMMA = 0.57721566490153286060651209

def generate_truncated_exponential_data(n, lam=1.0):

    u = np.random.uniform(0, 1, size=n)
    return -np.log(1 - u * (1 - np.exp(-lam))) / lam



from sklearn.neighbors import NearestNeighbors

def kl_entropy_estimator(data, k=1):

    n = len(data)
    data = data.reshape(-1, 1)

    # Compute distance to k-th nearest neighbor
    nbrs = NearestNeighbors(n_neighbors=k+1).fit(data)
    distances, _ = nbrs.kneighbors(data)

    # Skip the first column (distance to self is 0)
    rho = distances[:, k]  # distance to k-th nearest neighbor

    # Avoid log(0)
    rho = np.clip(rho, 1e-10, None)

    Hn = (1 / n) * np.sum(np.log(rho)) + psi(n) - psi(1) + np.log(2)
    return Hn

def direct_tail_entropy_power(tail_samples, total_samples):

    k = len(tail_samples)
    if k < 2 or total_samples < k:
        return np.nan
    w = tail_samples[-1]
    if w <= 0:
        return np.nan

    # Compute spacings
    spacings = np.diff(tail_samples)
    # Clip spacings to avoid log(0) or negative values
    spacings = np.maximum(spacings, 1e-10)

    log_geo_mean = np.mean(np.log(spacings))

    # Dimension m = 1 → c_1(m) = 2
    m = 1
    c_m = 2

    # Apply the KL estimator formula
    tail_entropy = kl_entropy_estimator(tail_samples)
    HP_tail = np.exp(tail_entropy)
    nHP_hat = HP_tail / w


    # Compute estimated tail entropy power and normalize
    #HP_direct = np.exp(H_direct)  # Tail entropy power: exp(estimated H)
    #nHP_hat = HP_direct / w       # Normalize by tail cutoff w
    return nHP_hat

def estimate_LID_MLE(tail_samples):

    k = len(tail_samples)
    if k < 2:
        return np.nan
    w = tail_samples[-1]
    if w <= 0:
        return np.nan
    logs = np.log(w / tail_samples[:-1])
    LID_est = 1 / np.mean(logs)
    return LID_est

def LID_based_nHP(LID_est):

    if LID_est <= 0:
        return np.nan
    return (1 / LID_est) * np.exp(1 - (1 / LID_est))

def compute_HP_trunc_exp_groundtruth(w, lambd):

    A = (1 - np.exp(-lambd * w))
    HP = (A/lambd) * np.exp(1 - ((lambd * w * np.exp(-lambd * w)) / A))
    nHP = HP / w
    return HP, nHP

# Experiment parameters
n = 1000             # total sample size
k_values = [10,20,50,75,100]  # different k values
N_iter = 500          # number of Monte Carlo iterations

results = {}

# Monte Carlo simulation for each k
for k in k_values:
    direct_estimates = []
    LID_based_estimates = []
    direct_times = []
    LID_times = []

    for i in range(N_iter):
        # Generate data and sort
        data = generate_truncated_exponential_data(n,2)
        data.sort()
        # Define tail region: first k points, with tail cutoff w = X_(k)
        tail_samples = data[:k]
        w = tail_samples[-1]
        _, ground_truth_nHP = compute_HP_trunc_exp_groundtruth(w, 2)


        # Direct tail entropy power estimation
        start_time = time.time()
        nHP_direct = direct_tail_entropy_power(tail_samples, n)
        direct_times.append(time.time() - start_time)

        # LID-based estimation
        start_time = time.time()
        LID_est = estimate_LID_MLE(tail_samples)
        nHP_LID = LID_based_nHP(LID_est)
        LID_times.append(time.time() - start_time)

        direct_estimates.append(nHP_direct)
        LID_based_estimates.append(nHP_LID)

    # Compute statistics
    direct_estimates = np.array(direct_estimates)
    LID_based_estimates = np.array(LID_based_estimates)

    direct_mean = np.nanmean(direct_estimates)
    direct_var = np.nanvar(direct_estimates)
    direct_bias2 = (direct_mean - ground_truth_nHP) ** 2
    direct_MSE = direct_bias2 + direct_var

    LID_mean = np.nanmean(LID_based_estimates)
    LID_var = np.nanvar(LID_based_estimates)
    LID_bias2 = (LID_mean - ground_truth_nHP) ** 2
    LID_MSE = LID_bias2 + LID_var

    results[k] = {
    'tail_cutoff_w': w,
    'ground_truth_nHP': ground_truth_nHP,
    'direct_mean': direct_mean,
    'direct_variance': direct_var,
    'direct_bias^2': direct_bias2,
    'direct_MSE': direct_MSE,
    'direct_avg_time_sec': np.mean(direct_times),
    'LID_mean': LID_mean,
    'LID_variance': LID_var,
    'LID_bias^2': LID_bias2,
    'LID_MSE': LID_MSE,
    'LID_avg_time_sec': np.mean(LID_times),
}


# Print the results for each k
for k, res in results.items():
    print(f"\nFor k = {k}:")
    print(f"    Ground truth tail entropy power = {res['ground_truth_nHP']:.8f}")
    print(f"  Tail cutoff w = {res['tail_cutoff_w']:.4f}")
    print("  Direct Estimator:")
    print(f"    Mean normalized tail entropy power = {res['direct_mean']:.4f}")
    print(f"    Variance = {res['direct_variance']:.6f}")
    print(f"    Squared Bias = {res['direct_bias^2']:.6f}")
    print(f"    MSE = {res['direct_MSE']:.6f}")
    print(f"    Avg. computation time = {res['direct_avg_time_sec']:.6e} sec")
    print("  LID-based Estimator:")
    print(f"    Mean normalized tail entropy power = {res['LID_mean']:.4f}")
    print(f"    Variance = {res['LID_variance']:.6f}")
    print(f"    Squared Bias = {res['LID_bias^2']:.6f}")
    print(f"    MSE = {res['LID_MSE']:.6f}")
    print(f"    Avg. computation time = {res['LID_avg_time_sec']:.6e} sec")

# Plot MSE vs. k
plt.figure(figsize=(10, 6))
plt.plot(k_values, [results[k]['direct_MSE'] for k in k_values], label='Direct Estimator MSE', marker='o')
plt.plot(k_values, [results[k]['LID_MSE'] for k in k_values], label='LID-based Estimator MSE', marker='s')
plt.xlabel('k (Number of Tail Samples)')
plt.ylabel('Mean Squared Error')
plt.title('MSE of Normalized Tail Entropy Power Estimators')
plt.legend()
plt.grid(True)
plt.savefig('tail_entropy_power_mse.png')

import numpy as np

def compute_HP_trunc_exp_groundtruth(w, lambd):

    A = 1 - np.exp(-lambd * w)
    HP = (A / lambd) * np.exp(1 -( (lambd * w * np.exp(-lambd * w)) / A))
    nHP = HP / w
    return HP, nHP

# Example usage:
w = 0.0068
lambd = 1.0
HP_exact, nHP_exact = compute_HP_trunc_exp_groundtruth(w, lambd)
print(f"Tail Entropy Power HP(F, w={w}) = {HP_exact:.6f}")
print(f"Normalized HP(F, w)/w = {nHP_exact:.6f}")